#!/usr/bin/env python3
"""Remove files produced by polyMorph search runs.

The script defaults to a dry run. Pass --apply to delete matched files.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


CONFIG_PATTERNS = (
    "*-result.json",
    "*-trials.csv",
    "*-cache.jsonl",
    "*-history.jsonl",
)

BENCH_FILE_PATTERNS = (
    "*.o",
    "*.d",
    "*-INFIX-*",
    "*-baseline",
    "*-search",
    "*-search-trial-*",
)

JSCOP_FILE_PATTERNS = (
    "*.jscop",
    "*.jscop.bak",
)

BENCH_DIR_NAMES = (
    "parser_logs",
)


def iter_matches(root: Path, include_build_dirs: bool) -> tuple[list[Path], list[Path]]:
    config_root = root / "configs" / "polyMorph"
    bench_root = root / "test-benchmarks" / "polyMorph"
    test_benchmarks_root = root / "test-benchmarks"
    files: set[Path] = set()
    dirs: set[Path] = set()

    if config_root.exists():
        for pattern in CONFIG_PATTERNS:
            files.update(path for path in config_root.rglob(pattern) if path.is_file())

    if bench_root.exists():
        for pattern in BENCH_FILE_PATTERNS:
            files.update(path for path in bench_root.rglob(pattern) if path.is_file())
        for name in BENCH_DIR_NAMES:
            dirs.update(path for path in bench_root.rglob(name) if path.is_dir())
        if include_build_dirs:
            dirs.update(path for path in bench_root.rglob("build") if path.is_dir())

    if test_benchmarks_root.exists():
        for pattern in JSCOP_FILE_PATTERNS:
            files.update(path for path in test_benchmarks_root.rglob(pattern) if path.is_file())

    files = {path for path in files if not any(parent in dirs for parent in path.parents)}
    return sorted(files), sorted(dirs)


def remove_paths(files: list[Path], dirs: list[Path]) -> None:
    for path in files:
        path.unlink(missing_ok=True)
    for path in sorted(dirs, key=lambda item: len(item.parts), reverse=True):
        shutil.rmtree(path, ignore_errors=True)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Clean files generated by polyMorph search runs.",
    )
    parser.add_argument(
        "--root",
        type=Path,
        default=Path.cwd(),
        help="Repository root. Defaults to the current directory.",
    )
    parser.add_argument(
        "--apply",
        action="store_true",
        help="Delete matched files. Without this flag, only prints a dry run.",
    )
    parser.add_argument(
        "--build-dirs",
        action="store_true",
        help="Also remove benchmark build directories.",
    )
    args = parser.parse_args()

    root = args.root.resolve()
    files, dirs = iter_matches(root, include_build_dirs=args.build_dirs)

    action = "Removing" if args.apply else "Would remove"
    directory_label = "directory" if len(dirs) == 1 else "directories"
    print(f"{action} {len(files)} file(s) and {len(dirs)} {directory_label}.")
    for path in [*dirs, *files]:
        print(path.relative_to(root) if path.is_relative_to(root) else path)

    if args.apply:
        remove_paths(files, dirs)
    else:
        print("\nDry run only. Re-run with --apply to delete these paths.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
